apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-message-across-service-bus-sender
spec:
  selector:
    matchLabels:
      app: send-message-across-service-bus-sender
  replicas: 1
  template:
    metadata:
      labels:
        app: send-message-across-service-bus-sender
    spec:
      # nodeSelector:
      #   "beta.kubernetes.io/os": linux
      containers:
      - name: send-message-across-service-bus-sender
        image: docker.io/yogiman/send-message-across-service-bus-sender
        ports:
        - containerPort: 8080
        env:
          - name: AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: service-bus-secrets
                key: connection-string
          - name: AZURE_SERVICEBUS_SAMPLE_TOPIC_NAME
            valueFrom:
              secretKeyRef:
                name: service-bus-secrets
                key: topic-name
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: application-insights-secrets
                key: instrumentation-key

---
apiVersion: v1
kind: Service
metadata:
  name: send-message-across-service-bus-sender
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: send-message-across-service-bus-sender
